logging:
  level: INFO
  loggers:
    net.mikc: DEBUG

peers:
  - http://localhost:8080

server:
  applicationConnectors:
  - type: http 
    port: 28000
  adminConnectors:
  - type: http
    port: 28001
